GET http://localhost:3001/api/notes

###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "content": "Bue"
}

###
DELETE http://localhost:3001/api/notes/68892d41ef7cf146ec9d4703